.TH "ftable" 3 "Sat Apr 13 2019" "Compilation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ftable
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBFUNentry\fP * \fBFtable\fP"
.br
.ti -1c
.RI "int \fBFsize\fP"
.br
.ti -1c
.RI "int \fBFmax\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Compilation from the source code\&.
