.TH "fun" 3 "Sat Apr 13 2019" "Compilation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fun
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [MAXNAME]"
.br
.ti -1c
.RI "int * \fBargs\fP"
.br
.ti -1c
.RI "int \fBNargs\fP"
.br
.ti -1c
.RI "int \fBMAXargs\fP"
.br
.ti -1c
.RI "int \fBreturn_type\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Compilation from the source code\&.
