.TH "Mtable" 3 "Sat Apr 13 2019" "Compilation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mtable
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMACROentry\fP * \fBMtable\fP"
.br
.ti -1c
.RI "int \fBMsize\fP"
.br
.ti -1c
.RI "int \fBMmax\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Compilation from the source code\&.
