.TH "cel" 3 "Sat Apr 13 2019" "Compilation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cel
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBSTentry\fP * \fBSTtable\fP"
.br
.ti -1c
.RI "\fBCONSTentry\fP * \fBCtable\fP"
.br
.ti -1c
.RI "int \fBSTmax\fP"
.br
.ti -1c
.RI "int \fBSTsize\fP"
.br
.ti -1c
.RI "int \fBCmax\fP"
.br
.ti -1c
.RI "int \fBCsize\fP"
.br
.ti -1c
.RI "int \fBcurrent_stack_address\fP"
.br
.ti -1c
.RI "struct \fBcel\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Compilation from the source code\&.
