.TH "MACROentry" 3 "Sat Apr 13 2019" "Compilation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MACROentry \- define a struct for a macro constante\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <decl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [MAXNAME]"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "float \fBvalueFloat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
define a struct for a macro constante\&. 

\fBMACROentry\fP is a name, a type and a value\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Compilation from the source code\&.
